### ISSUE TITLE
About ShanghaiTech Campus dataset (Anomaly Detection)

### ISSUE THREAD

**Issue by Markovcom** [StevenLiuWen/sRNN_TSC_Anomaly_Detection#10]
Hello, there are 130 anomaly events in this dataset introduced by your paper. What are these anomaly types specifically?

**Comment by zachluo** [comment]
[semantic_annotation.zip](https://github.com/StevenLiuWen/sRNN_TSC_Anomaly_Detection/files/3976954/semantic_annotation.zip)
Hi @Markovcom ,
I have uploaded two semantic annotation of ShanghaiTech and Avenue.

**Comment by Markovcom** [comment]
@zachluo Thank you very much，do you have similar annotation files for UCSD Ped1 or Ped2?

**Comment by zachluo** [comment]
@Markovcom I don't have them for Ped1 and Ped2 since we only evaluate our method in IJCAI on ShanghaiTech and Avenue.

**Comment by Markovcom** [comment]
@zachluo Thank you all the same.

**Comment by Markovcom** [comment]
@zachluo Can you explain the format of the annotation file？
![image](https://user-images.githubusercontent.com/26458922/71066749-3b3b7580-21ae-11ea-8901-fd584f3e169d.png)

**Comment by zachluo** [comment]
@Markovcom '0001' is the video id and in this video there are two anomalies. One is chasing at Frame #[1, 169] U [172, 177] and another one is jumping at Frame #[385, 385] U [387, 500].

**Comment by Markovcom** [comment]
@zachluo Thank you very much.

**Comment by youngupup** [comment]
@zachluo 你好请问shanghaitech数据集测试集的时长是多长？
