### ISSUE TITLE
How can I find the h5 file of avenue?

### ISSUE THREAD

**Issue by Holdwsq** [StevenLiuWen/sRNN_TSC_Anomaly_Detection#13]
load_optical_flow_path = '/home/luowx/datasets/avenue/testing/224/optical_flow/';
In the code, using the h5 file of avenue  to preprocess optical_flow, but I don't have the file, Please tell me how find it. Thank you!

**Comment by zachluo** [comment]
@Holdwsq  We use the difference of image features as motion rather than optical flow features. So, we don't save the optical flow files due to the large demand of disks.

**Comment by Holdwsq** [comment]
> @Holdwsq We use the difference of image features as motion rather than optical flow features. So, we don't save the optical flow files due to the large demand of disks.

Thank you!

**Comment by Holdwsq** [comment]
> @Holdwsq We use the difference of image features as motion rather than optical flow features. So, we don't save the optical flow files due to the large demand of disks.

Hello, I'm a rookie in this field, but I'm very interested in it
May I ask you a few more questions?
1.DOIF（difference of image features）means: Is feature subtraction extracted from video frame (RGB file)？Can you explain it in detail？
2.What are the advantages of DOIF compared with optical flow characteristics？

Can you give me some code examples to learn？thank you very much indeed！

**Comment by zachluo** [comment]
@Holdwsq Please refer to our journal paper:
https://ieeexplore.ieee.org/document/8851288
We explain that in Section 4.7.
