### ISSUE TITLE
about standard of evalution

### ISSUE THREAD

**Issue by wanboyang** [StevenLiuWen/sRNN_TSC_Anomaly_Detection#5]
Hi, I have a question about your compute_auc  function in https://github.com/StevenLiuWen/sRNN_TSC_Anomaly_Detection/blob/1dc9a288ff18f37d10868188b275756a7d802dc6/evaluate.py#L154.
======================================================
        for i in range(num_videos):
            distance = mse_records[i]

            distance -= distance.min()    # distances = (distance - min) / (max - min)
            distance /= distance.max()
            distance = 1 - distance
	    #distance = distance[:,0]

            scores = np.concatenate((scores, distance), axis=0)
            labels = np.concatenate((labels, gt[i]), axis=0)
======================================================
Does this mean that every test video is normalized? Does this result in an area with a regularity score 0 in every test video, regardless of whether the video is normal or not?

**Comment by zachluo** [comment]
Yes, Since most of anomaly detection datasets hold all abnormal videos in the testing set, we normalize every test video.

**Comment by wanboyang** [comment]
> @wanboyang Yes, Since most of anomaly detection datasets hold all abnormal videos in the testing set, we normalize every test video.

Thank you for  replying

**Comment by youngupup** [comment]
@wanboyang ,hi,in  evaluate.py  there is an error with 'from tools.ground_truth import GroundTruthLoader',As a beginner, I don't know how to solve it? If you know, please point me out, thank you
